name: emoji_viewer
description: "A viewer for emoji metadata."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0-99.1.beta <4.0.0"

dependencies:
  backstreets_widgets: ^0.9.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  path: ^1.9.0
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/emoji_15_1_ordering.json
    - assets/emoticon_ordering.json
